### ISSUE TITLE
PullRequest constructor returns what?

### ISSUE THREAD

**Issue by remarcmij** [PRB0t/PRB0t#15]
The constructor returns what and wherefore??

**Comment by M3kH** [comment]
Returns a promise, is this an issue?

**Comment by remarcmij** [comment]
Perhaps it is just a lack of understanding from my side and is this a novel way of using classes that I haven't come across yet, but it seems to me that you can't (externally) call any of the methods on the PullRequest object if you create an instance of it with `new`. This because it seems you are not returning an instance of PullRequest but instead an instance of Promise. Granted, you do not expect any of its methods to be called externally...

**Comment by M3kH** [comment]
Yep. You're right!
Design wise, could be confusing, in the first instance. 

*But I will try to elaborate on that:*
*... IMO...*
- **Choosing Class** is just, handy and clean way, to build an Object that relays in the a *state*, *scope*, *methods (private/public)*.
- **Returns a promise**, because is clean to consuming and is not that much different from `new Promise()` + you could `await new PullRequest(...)` simple has that. I though about, ...is a bit wired, but I still claim it as valid choice.
- The **resolve returns the detail of a [PR] (https://developer.github.com/v3/pulls/#create-a-pull-request)**. You could do something like `const { data } = new PullRequest(...)`

@remarcmij Have a look what @timneutkens 😎 did in #16
I think is a neat start, and is ready to be consumed with other kinds of implementations/setups.

*And then...* I do like the concept of `service`, `do one thing good`. 
Maybe should be documented, with some comments.
But also let's be honest the strong point is the consumable endpoint, this is not a module... yet.. :-)

But I would like to know more how you think can be structured better; and which API deliver.
If you have ideas I will be glad to hear them.

For now, Thanks 🙏

**Comment by remarcmij** [comment]
You could use `XMLHttpRequest` as a model. It is similar in usage: you create an once-off instance with `new`, configure it by using its methods and properties, fire it off, wait for the results and finally turn it over to the garbage collector.

So your `PullRequest` class could follow the same principle, e.g.:

```js
const pr = new PullRequest();
pr.configure(...);
try {
  const result = await pr.send();
  ...
} catch (error) {
 ...
}
```

This code would still do what you want, but now using a familiar, trusted scheme. What do you think?

EDIT:

Or you  could follow the model of `fetch` if you prefer a single line and keep your class as an internal implementation detail:

```js
import pullRequest from '...'

...

const await result = pullRequest(...);
```

You could just expose a `pullRequest` function rather than the class itself. This function would do the `new` etc for you.

**Comment by M3kH** [comment]
The issue has been resolve.
Thanks @remarcmij 👍
